# Table for storing session data. 
CREATE TABLE IF NOT EXISTS `ci_sessions` (
`id` varchar(40) NOT NULL,
`ip_address` varchar(45) NOT NULL,
`timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
`data` blob NOT NULL,
KEY `ci_sessions_timestamp` (`timestamp`)
);

CREATE TABLE menuItem (
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    price DECIMAL(5,2) NOT NULL,
    category INTEGER);
	
CREATE TABLE category (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25) NOT NULL);
		
ALTER TABLE menuItem ADD CONSTRAINT fk_menuitem_has_category
	FOREIGN KEY (category) REFERENCES category(ID) 
	ON UPDATE CASCADE ON DELETE CASCADE; 
	
CREATE TABLE reservation (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    email VARCHAR(100), 
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    due TIMESTAMP NOT NULL,
	cancelled TINYINT(1) DEFAULT 0,
	completed TINYINT(1) DEFAULT 0);
	
CREATE TABLE reservationItems (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	reservation INTEGER NOT NULL,
	menuItem INTEGER NOT NULL,
	amount INTEGER DEFAULT 1);
	
ALTER TABLE reservationItems ADD CONSTRAINT fk_reservationItems_have_reservation
	FOREIGN KEY (reservation) REFERENCES reservation(ID)
	ON UPDATE CASCADE ON DELETE CASCADE;
	
ALTER TABLE reservationItems ADD CONSTRAINT fk_reservationItems_have_menuItems
	FOREIGN KEY (menuItem) REFERENCES menuItem(ID) 
	ON UPDATE CASCADE ON DELETE RESTRICT;
	
CREATE TABLE location (
	ID INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(10) NOT NULL,
	aadress VARCHAR(100));
	
CREATE TABLE employee (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(15),
    lastName VARCHAR(25),
    title VARCHAR(25),
    phone VARCHAR(15),
    email VARCHAR(100));
	
ALTER TABLE employee ADD COLUMN location INTEGER NOT NULL;

ALTER TABLE employee ADD CONSTRAINT fk_employee_has_location
	FOREIGN KEY (location) REFERENCES location(ID) ON UPDATE CASCADE ON DELETE RESTRICT;
	
ALTER TABLE menuItem ADD COLUMN
	location INTEGER NOT NULL;
	
ALTER TABLE reservation ADD COLUMN
	location INTEGER NOT NULL;
	
ALTER TABLE menuItem ADD CONSTRAINT fk_menuitem_has_location
	FOREIGN KEY (location) REFERENCES location(ID) ON UPDATE CASCADE ON DELETE RESTRICT;
	
ALTER TABLE reservation ADD CONSTRAINT fk_reservation_has_location
	FOREIGN KEY (location) REFERENCES location(ID) ON UPDATE CASCADE ON DELETE RESTRICT;